/** @format */

const bookings = [
  {
    id: 1,
    customerName: "John",
    roomName: "Room 1",
    noOfSeatsAvailable: 4,
    amenties: ["restaurants", "parks", "community centres", "swimming pools"],
    price: 10,
    Date: "04/20/2024",
    startTime: "10:10 AM",
    endTime: "05:00 PM",
    bookingId: "11",
    bookingDate: "01/20/2024",
    bookingStatus: true,
  },
  {
    id: 2,
    customerName: "syed",
    roomName: "Room 2",
    noOfSeatsAvailable: 2,
    amenties: ["restaurants", "parks"],
    price: 20,
    Date: "01/20/2024",
    startTime: "09:10 AM",
    endTime: "05:00 PM",
    bookingId: "12",
    bookingDate: "01/20/2024",
    bookingStatus: true,
  },
  {
    id: 3,
    customerName: "Imran",
    roomName: "Room 3",
    noOfSeatsAvailable: 10,
    amenties: ["restaurants", "parks", "community centres", "swimming pools"],
    price: 10,
    Date: "03/10/2024",
    startTime: "05:10 AM",
    endTime: "06:00 PM",
    bookingId: "13",
    bookingDate: "02/29/2024",
    bookingStatus: true,
  },
  {
    id: 4,
    customerName: "Umar",
    roomName: "Room 4",
    noOfSeatsAvailable: 4,
    amenties: ["restaurants", "parks", "community centres", "swimming pools"],
    price: 40,
    Date: "04/20/2024",
    startTime: "11:10 AM",
    endTime: "05:00 PM",
    bookingId: "14",
    bookingDate: "01/20/2024",
    bookingStatus: false,
  },
  {
    id: 5,
    customerName: "kaleel",
    roomName: "Room 5",
    noOfSeatsAvailable: 4,
    amenties: ["restaurants", "parks", "community centres", "swimming pools"],
    price: 25,
    Date: "04/22/2024",
    startTime: "10:10 AM",
    endTime: "05:00 PM",
    bookingId: "15",
    bookingDate: "01/18/2024",
    bookingStatus: true,
  },
  {
    id: 6,
    customerName: "sheriff",
    roomName: "Room 6",
    noOfSeatsAvailable: 4,
    amenties: ["restaurants", "parks", "community centres", "swimming pools"],
    price: 16,
    Date: "04/15/2024",
    startTime: "05:10 AM",
    endTime: "05:00 PM",
    bookingId: "16",
    bookingDate: "01/20/2024",
    bookingStatus: true,
  },
];

module.exports = { bookings };
